// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuiviVaccinationCovidCodeFirst.Modeles;

#nullable disable

namespace SuiviVaccinationCovidCodeFirst.Migrations
{
    [DbContext(typeof(VaccinationContext))]
    partial class VaccinationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SuiviVaccinationCovidCodeFirst.Modeles.Immunisation", b =>
                {
                    b.Property<int>("ImmunisationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImmunisationId"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAMPatient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImmunisationId");

                    b.ToTable("Immunizations");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Immunisation");
                });

            modelBuilder.Entity("SuiviVaccinationCovidCodeFirst.Modeles.Vaccin", b =>
                {
                    b.Property<int>("VaccinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VaccinId"), 1L, 1);

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VaccinId");

                    b.ToTable("Vaccins");
                });

            modelBuilder.Entity("SuiviVaccinationCovidCodeFirst.Modeles.Covid19", b =>
                {
                    b.HasBaseType("SuiviVaccinationCovidCodeFirst.Modeles.Immunisation");

                    b.Property<int>("Covid19Id")
                        .HasColumnType("int");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Covid19");
                });

            modelBuilder.Entity("SuiviVaccinationCovidCodeFirst.Modeles.Dose", b =>
                {
                    b.HasBaseType("SuiviVaccinationCovidCodeFirst.Modeles.Immunisation");

                    b.Property<int>("DoseId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroDose")
                        .HasColumnType("int");

                    b.Property<int>("VaccinId")
                        .HasColumnType("int");

                    b.HasIndex("VaccinId");

                    b.HasDiscriminator().HasValue("Dose");
                });

            modelBuilder.Entity("SuiviVaccinationCovidCodeFirst.Modeles.Dose", b =>
                {
                    b.HasOne("SuiviVaccinationCovidCodeFirst.Modeles.Vaccin", "Vaccin")
                        .WithMany()
                        .HasForeignKey("VaccinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vaccin");
                });
#pragma warning restore 612, 618
        }
    }
}
